#!/usr/bin/env groovy

pipeline {
    agent {
        docker {
            image 'node:latest'
            args '-v /var/www/elements/html:/var/lib/jenkins/workspace/elements-api-front/elements-webapp/build -u root'
        }
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                dir('elements-webapp') {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
    }
}
